### ISSUE TITLE
Nice repo banner 👍

### ISSUE THREAD

**Issue by Nit-nit** [anas-elgarhy/anas-elgarhy#13]
Yo i just got you recommended in my feed, well that's a nice repo banner and i liked it, it's instantly gonna make anyone click on your readme, nice! And the way you have wrote your readme is also awesome.

![Screenshot_20220725-092243.png](https://user-images.githubusercontent.com/94877880/180695730-99a0aba7-49c8-4f79-b40f-2835d0801a6d.png)

Now I think I need to put one on my readme too lmaooo.
Well sorry to open an issue, this is all I had to say, gotta close it quick 😅

**Comment by anas-elgarhy** [comment]
Thanks❤, Actually it was a random choice 😂

**Comment by Nit-nit** [comment]
Nice choice tbh 😎
