### ISSUE TITLE
Woww

### ISSUE THREAD

**Issue by XFaonAE** [anas-elgarhy/anas-elgarhy#14]
cool profile

**Comment by anas-elgarhy** [comment]
Thanks ❤️

**Comment by XFaonAE** [comment]
do you have Discord?

**Comment by anas-elgarhy** [comment]
Yes, my username `;; #8946`
I also have a discord server 😃, but he doesn't have much activity right now 🥲

**Comment by XFaonAE** [comment]
Ty

**Comment by anas-elgarhy** [comment]
I'm so glad I got to know you 💙
